language: ruby
rvm:
  - 2.6.1
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle install --jobs=3 --retry=3 --deployment
  - bin/rails db:create
  - bin/rails db:migrate
  - bundle exec rspec